### PR TITLE
Fixes cancel button styling for offerings

### LINKED ISSUE #283: When creating an offer, 'Cancel' button shouldn't be washed out
Feel like the styling on the cancel button is too washed out, doesn't feel like I should be able to press it.

# Before

before

# After

after

### PR DESCRIPTION
**Pull request by benzap**
- fixes #283

### CODE REVIEW

File: src/memefactory/styles/base/colors.clj [hunk 1]
```diff
@@ -45,7 +45,7 @@
                     :busy-grey "#5c5c5c"
                     :rank-yellow "#ffd800"
                     :yellow "#ffea00"
-                    :cancel-button "#d0e5e8"
+                    :cancel-button "#ff0094"
```
Comment (madvas) [inline src/memefactory/styles/base/colors.clj]: Why not using `:pink` we already have here?

Comment (benzap) [reply src/memefactory/styles/base/colors.clj]: yeah, i'll just use the pink
