### PR TITLE
Parameters table structure and syncing redesign Fixes #569 Fixes #568

### LINKED ISSUE #568: SqliteError: UNIQUE constraint failed: initial_params.initial_param_SLASH_key, initial_params.initial_param_SL...
Sentry Issue: [MEMEFACTORY-11N](https://sentry.io/organizations/district0x/issues/1130786840/?referrer=github_integration)

```
SqliteError: UNIQUE constraint failed: initial_params.initial_param_SLASH_key, initial_params.initial_param_SLASH_db
  File "/memefactory/server/memefactory.js", line 9424, in district.server.db.run_BANG_
    '{snip} ljs.core.deref.call(null,district.server.db.db).prepare(a).run(cljs.core.clj__GT_js.call(null,b?b:cljs.core.PersistentVector.EMPTY)),new clj {snip}
  File "/memefactory/server/memefactory.js", line 9763, in memefactory.server.db.insert_initial_params_BANG_
    '{snip} rams_BANG_=function(a){return district.server.db.run_BANG_.call(null,new cljs.core.PersistentArrayMap(null,2,[new cljs.core.Keyword(null,"in {snip}
  File "/memefactory/server/memefactory.js", line 11665, in memefactory.server.syncer.eternal_db_event
    '{snip} ,h,k,l,b,a,c,d),cljs.core.PersistentVector.EMPTY,l);return Promise.resolve(memefactory.server.db.insert_initial_params_BANG_.call(null,b))};
  File "/memefactory/server/memefactory.js", line 11683, in null.<anonymous>
    '{snip} g,h,l,q,r,t,u,v,w,x,y,z,A,c,d,e,k),null),null,568569239),a.call(null,b,g).then(function(a,b,c,d,e,f,g,h,k,l,m,n,p,q,r,t,u){return function() {snip}

SqliteError: UNIQUE constraint failed: initial_params.initial_param_SLASH_key, initial_params.initial_param_SLASH_db
```

### LINKED ISSUE #569: Parameters table structure and syncing redesign
Store parameters information in two tables,

Parameters, will have one row per parameter which are going to be updated in place with EternalDB events.

ParamChanges, will keep track of ParamChangeRegistry

Fix graphql resolvers accordingly

### PR DESCRIPTION
**Pull request by jpmonettas**

### CODE REVIEW

File: src/memefactory/server/syncer.cljs [hunk 1]
```diff
@@ -301,15 +301,12 @@
...
-        rows (reduce (fn [res [k v]]
-                       (conj res {:initial-param/key k
-                                  :initial-param/db address
-                                  :initial-param/value (bn/number v)
-                                  :initial-param/set-on timestamp}))
-                     []
-                     keys->values)]
-    (js/Promise.resolve (db/insert-initial-params! rows))))
+                          (into {}))]
+    (js/Promise.resolve (doseq [[k v] keys->values]
```
Comment (fbielejec) [inline src/memefactory/server/syncer.cljs]: no need for a loop here - upsert should work with multiple rows too - lets limit the number of db operations

File: src/memefactory/server/syncer.cljs [hunk 2]
```diff
@@ -148,7 +148,7 @@
                        :param-change/db db
                        :param-change/key key
                        :param-change/value (bn/number value)
-                       :param-change/original-value (:param/value (db/get-param key db))
+                       :param-change/original-value (:param/value (first (db/get-all-params db [key])))
```
Comment (fbielejec) [inline src/memefactory/server/syncer.cljs]: since you use get-all and then use `first` on the result, why not just write SQL that retrieves one row?

File: src/memefactory/server/graphql_resolvers.cljs [hunk 3]
```diff
@@ -361,23 +361,8 @@
...
-                                             :from [:initial-params]
-                                             :where [:and [:= key :initial-params.initial-param/key]
-                                                     [:= db :initial-params.initial-param/db]]}]
-                   (paged-query initial-params-query
-                                first
-                                (when after
-                                  (js/parseInt after))))))]
-     ret)))
+                                             (js/parseInt after)))]
+     param-changes-result)))
```
Comment (fbielejec) [inline src/memefactory/server/graphql_resolvers.cljs]: This resolver is for retrieving changes with all their history. Why not write a simple `current-parameters-query-resolver [:key :db]` resolver that just runs queries over`:param-changes` table for the client? Faster and with less room for an error.

Comment (jpmonettas) [reply src/memefactory/server/graphql_resolvers.cljs]: Sorry, not following here, the params value are coming from parameters table, this is for param changes where there is nothing as "current param changes"

File: src/memefactory/server/syncer.cljs (hunk 1 above)
Comment (jpmonettas) [reply src/memefactory/server/syncer.cljs]: I'm not worried about perf here since this is only going to be called on parameter change apply so once in a while, and we are only talking about the order of 10 rows always. But it isn't hard to change neither

File: src/memefactory/server/syncer.cljs (hunk 2 above)
Comment (jpmonettas) [reply src/memefactory/server/syncer.cljs]: Same as other comment, not worried about perf, this code is only going to execute on param change creation so very rarely, and when it does it deals with about 10 rows always. But if you think it is important we can change it OC.

File: src/memefactory/server/syncer.cljs (hunk 1 above)
Comment (fbielejec) [reply src/memefactory/server/syncer.cljs]: It's just that I was very careful to avoid unnecessary db operations when re-designing how we do persistance, introduced upserts instead of if-exists patterns and bulk inserts wherever possible. This is more performant and will pay off if we decide to go for a regular database. Not to mention that here you get it for free, you have the code that turns the data into insertable rows, you can just use it.

File: src/memefactory/server/syncer.cljs (hunk 2 above)
Comment (fbielejec) [reply src/memefactory/server/syncer.cljs]: Similar reasons as above, lets keep the db operations performant and it will pay off in the future. :)

File: src/memefactory/server/graphql_resolvers.cljs (hunk 3 above)
Comment (fbielejec) [reply src/memefactory/server/graphql_resolvers.cljs]: I though we talked about having two endpoints in the end - one for parameter changes one for current parameter values. I have looked at the client code and it actually looks like this endpoint is called just once, at boot and persisted in re-frame db, so it's all good I guess.

File: src/memefactory/server/syncer.cljs (hunk 2 above)
Comment (jpmonettas) [reply src/memefactory/server/syncer.cljs]: Well this is returning one row already, changed the name to get-params to make it  more clear.
