### PR TITLE
Fix #505 (Fix keys in EternalDB with correct sha3 function)

### LINKED ISSUE #505: Fix keys in EternalDB with correct sha3 function
We've encoded initial parameters EternalDBs with wrong sha3 function https://github.com/district0x/memefactory/blob/2d731ef3d6fb8c7e6c1cd8b01b2c2f058562d673/migrations/2_memefactory_migration.js#L229. 

This will cause trouble, because in ParamChange contract we're using solidity's sha3, which is different from web3.sha3: https://github.com/district0x/memefactory/blob/6951aa05c6882424f4552d408551157c1bbe0517/contracts/ParamChange.sol#L45

Everything works at the moment, because we're decoding it with the same wrong function: 
https://github.com/district0x/memefactory/blob/fc30420e1297c015fb69a3cf1cccca4667c5c7ea/src/memefactory/server/syncer.cljs#L344
But when we'll start using param changes, it'll not work. 

Solution: 
1. Correct initial migration to use [solidity-sha3](https://github.com/raineorshine/solidity-sha3/).
2. Write migration script that sets correct keys in existing eternal dbs (memeRegistryDb, paramChangeRegistryDb)
3. Fix syncer.cljs to use https://github.com/district0x/cljs-solidity-sha3

### PR DESCRIPTION
**Pull request by jpmonettas**

### CODE REVIEW

File: project.clj [hunk 1]
```diff
@@ -117,7 +117,10 @@
                        [jsedn "0.4.1"]
                        ;; for twitter bot
                        [twitter "1.7.1"]
-                       [tar-fs "2.0.0"]]}
+                       [tar-fs "2.0.0"]
+                       ;; for solidity sha3 function
+                       [web3-utils "1.0.0-beta.55"]
```
Comment (fbielejec) [inline project.clj]: LGTM, personally I'd copy the solution from https://github.com/raineorshine/solidity-sha3/blob/master/src/index.js into utils.js, but YMMV
