### PR TITLE
Fixed 'Stank' tags, added hover animation

### LINKED ISSUE #242: Rejected tape improvements
Rejected tape is cool, but needs following improvements: 
1. Change [this line](https://github.com/district0x/memefactory/blob/5d3102f7977b4cd1f9936abede40c7b8ab7c8d18/src/memefactory/styles/component/compact_tile.clj#L344) to `(px (- (/ card-height 2) 45))`
2. Add to My Memefolio - Curated. Currently tape is not shown there
3. On hover, the tape should fade out (CSS animation), including dimmed overlay, so users can view the card normally if desired. 

image

### PR DESCRIPTION
**Pull request by benzap**
- changed positioning a bit as suggested
- added correct gql rulings to get the status for curated pages
- added hover animation to reveal original meme without the 'stank' badge
- fixes #242

### CODE REVIEW

File: src/memefactory/ui/memefolio/page.cljs [hunk 1]
```diff
@@ -491,6 +491,7 @@
                           :meme/image-hash :meme/number
                           :meme/title :challenge/vote] :as meme}]
                (when address
+                 (.log js/console (clj->js meme))
```
Comment (madvas) [inline src/memefactory/ui/memefolio/page.cljs]: This is forgotten?

Comment (benzap) [reply src/memefactory/ui/memefolio/page.cljs]: Woops! I'll get rid of that
